-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 16:32:13 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Match`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Match` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Match` (
  `Match_id` INT NOT NULL,
  `Match_ingameid` VARCHAR(45) NULL,
  `Detail` VARCHAR(45) NULL,
  `Winner` VARCHAR(45) NULL,
  PRIMARY KEY (`Match_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Hero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Hero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Hero` (
  `hero_id` INT NOT NULL,
  `hero_name` VARCHAR(45) NULL,
  `hero_name2` VARCHAR(45) NULL,
  `win` VARCHAR(45) NULL,
  `lose` VARCHAR(45) NULL,
  PRIMARY KEY (`hero_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Match_has_Hero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Match_has_Hero` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Match_has_Hero` (
  `Match_Match_id` INT NOT NULL,
  `Hero_hero_id1` INT NOT NULL COMMENT '1st hero\n',
  `Hero_hero_id2` INT NOT NULL COMMENT '2nd hero',
  `Hero_hero_id3` INT NOT NULL COMMENT '3th hero',
  `Hero_hero_id4` INT NOT NULL COMMENT '4th hero',
  `Hero_hero_id5` INT NOT NULL COMMENT '5th hero',
  PRIMARY KEY (`Match_Match_id`, `Hero_hero_id1`, `Hero_hero_id2`, `Hero_hero_id3`, `Hero_hero_id4`, `Hero_hero_id5`),
  INDEX `fk_Match_has_Hero_Hero1_idx` (`Hero_hero_id1` ASC) VISIBLE,
  INDEX `fk_Match_has_Hero_Match_idx` (`Match_Match_id` ASC) VISIBLE,
  INDEX `fk_Match_has_Hero_Hero2_idx` (`Hero_hero_id5` ASC) VISIBLE,
  INDEX `fk_Match_has_Hero_Hero3_idx` (`Hero_hero_id2` ASC) VISIBLE,
  INDEX `fk_Match_has_Hero_Hero4_idx` (`Hero_hero_id3` ASC) VISIBLE,
  INDEX `fk_Match_has_Hero_Hero5_idx` (`Hero_hero_id4` ASC) VISIBLE,
  CONSTRAINT `fk_Match_has_Hero_Match`
    FOREIGN KEY (`Match_Match_id`)
    REFERENCES `mydb`.`Match` (`Match_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_has_Hero_Hero1`
    FOREIGN KEY (`Hero_hero_id1`)
    REFERENCES `mydb`.`Hero` (`hero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_has_Hero_Hero2`
    FOREIGN KEY (`Hero_hero_id5`)
    REFERENCES `mydb`.`Hero` (`hero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_has_Hero_Hero3`
    FOREIGN KEY (`Hero_hero_id2`)
    REFERENCES `mydb`.`Hero` (`hero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_has_Hero_Hero4`
    FOREIGN KEY (`Hero_hero_id3`)
    REFERENCES `mydb`.`Hero` (`hero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Match_has_Hero_Hero5`
    FOREIGN KEY (`Hero_hero_id4`)
    REFERENCES `mydb`.`Hero` (`hero_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
